name: blogs
timestamp: 1703766150
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1702605628
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  owlcarousel:
    owlcarousel-8948: 'Owl Carousel'
  content:
    system-content-6646: 'Page Content'
  mobile-menu:
    mobile-menu-5697: Mobile-menu
  messages:
    system-messages-6359: 'System Messages'
  logo:
    logo-2134: 'Logo / Image'
  spacer:
    spacer-5908: Spacer
    spacer-1124: Spacer
    spacer-3065: Spacer
  menu:
    menu-6569: Menu
  custom:
    custom-4733: 'Custom HTML'
    custom-6934: 'Custom HTML'
    custom-4018: 'Custom HTML'
inherit:
  default:
    navigation: navigation
    footer: footer
    system-messages-6359: system-messages-7972
    logo-2134: logo-9608
    spacer-5908: spacer-2211
    menu-6569: menu-6409
    custom-4733: custom-9191
    custom-6934: custom-2229
    spacer-1124: spacer-9913
    custom-4018: custom-5952
    spacer-3065: spacer-2150
