version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1702605628
layout:
  navigation: {  }
  /header/:
    -
      - owlcarousel-8948
    -
      - system-content-6646
  /intro/: {  }
  /features/: {  }
  /utility/: {  }
  /above/: {  }
  /testimonials/: {  }
  /expanded/: {  }
  /container-main/:
    -
      -
        'aside 25': {  }
      -
        'mainbar 50': {  }
      -
        'sidebar 25': {  }
  footer: {  }
  /offcanvas/:
    -
      - mobile-menu-5697
structure:
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  header:
    attributes:
      boxed: ''
      class: g-flushed
      variations: ''
  intro:
    type: section
    attributes:
      boxed: ''
  features:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
  above:
    type: section
    attributes:
      boxed: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  aside:
    attributes:
      class: ''
    block:
      fixed: '1'
  mainbar:
    type: section
    subtype: main
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: ''
    block:
      fixed: '1'
  container-main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    attributes:
      boxed: ''
content:
  owlcarousel-8948:
    title: 'Owl Carousel'
    attributes:
      items:
        -
          class: ''
          image: 'gantry-media://header/about-header.png'
          title: '<div id="about-title">  <h1> <span>About Us</span></h1> <p>Unlock the door to your<br>dream house with us &#8594;</p> </div>'
          desc: ''
          link: ''
          linktext: ''
          buttonclass: button-outline
          disable: '0'
          name: 'Item 1'
