name: property_shop
timestamp: 1703766150
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1702605628
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-5423: 'System Messages'
  logo:
    logo-8427: 'Logo / Image'
  spacer:
    spacer-3882: Spacer
    spacer-2918: Spacer
    spacer-5550: Spacer
  menu:
    menu-3695: Menu
  custom:
    custom-4886: 'Custom HTML'
    custom-6885: 'Custom HTML'
  content:
    system-content-6646: 'Page Content'
  mobile-menu:
    mobile-menu-5697: Mobile-menu
inherit:
  default:
    system-messages-5423: system-messages-7972
    logo-8427: logo-9608
    spacer-3882: spacer-2211
    menu-3695: menu-6409
    custom-4886: custom-9191
    footer: footer
    spacer-2918: spacer-9913
    custom-6885: custom-5952
    spacer-5550: spacer-2150
