version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1702605628
layout:
  /navigation/:
    -
      - system-messages-5423
    -
      - 'logo-8427 15'
      - 'spacer-3882 20'
      - 'menu-3695 40'
      - 'custom-4886 25'
  /header/: {  }
  /intro/: {  }
  /features/:
    -
      - system-content-6646
  /utility/: {  }
  /above/: {  }
  /testimonials/: {  }
  /expanded/: {  }
  /container-main/:
    -
      -
        'aside 25': {  }
      -
        'mainbar 50': {  }
      -
        'sidebar 25': {  }
  footer: {  }
  /offcanvas/:
    -
      - mobile-menu-5697
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  header:
    attributes:
      boxed: ''
      class: g-flushed
      variations: ''
  intro:
    type: section
    attributes:
      boxed: ''
  features:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
  above:
    type: section
    attributes:
      boxed: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  aside:
    attributes:
      class: ''
    block:
      fixed: '1'
  mainbar:
    type: section
    subtype: main
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: ''
    block:
      fixed: '1'
  container-main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    attributes:
      boxed: ''
content:
  system-messages-5423:
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: system-messages-7972
  logo-8427:
    title: 'Logo / Image'
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: logo-9608
  spacer-3882:
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: spacer-2211
  menu-3695:
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: menu-6409
  custom-4886:
    title: 'Custom HTML'
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: custom-9191
