name: home_-_particles
timestamp: 1703766150
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1702605628
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  owlcarousel:
    owlcarousel-2455: 'Owl Carousel'
  content:
    system-content-3009: 'Page Content'
  messages:
    system-messages-3429: 'System Messages'
  logo:
    logo-3134: 'Logo / Image'
  spacer:
    spacer-2159: Spacer
    spacer-8471: Spacer
    spacer-1153: Spacer
  menu:
    menu-4076: Menu
  custom:
    custom-5118: 'Custom HTML'
    custom-1158: 'Custom HTML'
    custom-4827: 'Custom HTML'
  mobile-menu:
    mobile-menu-8940: Mobile-menu
inherit:
  default:
    navigation: navigation
    footer: footer
    offcanvas: offcanvas
    system-messages-3429: system-messages-7972
    logo-3134: logo-9608
    spacer-2159: spacer-2211
    menu-4076: menu-6409
    custom-5118: custom-9191
    custom-1158: custom-2229
    spacer-8471: spacer-9913
    custom-4827: custom-5952
    spacer-1153: spacer-2150
    mobile-menu-8940: mobile-menu-5697
