name: property
timestamp: 1703766150
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1702605628
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  owlcarousel:
    owlcarousel-8948: 'Owl Carousel'
  content:
    system-content-6646: 'Page Content'
  mobile-menu:
    mobile-menu-5697: Mobile-menu
  messages:
    system-messages-2702: 'System Messages'
  logo:
    logo-3313: 'Logo / Image'
  spacer:
    spacer-9268: Spacer
    spacer-4819: Spacer
    spacer-6169: Spacer
  menu:
    menu-7641: Menu
  custom:
    custom-9650: 'Custom HTML'
    custom-2242: 'Custom HTML'
    custom-3224: 'Custom HTML'
inherit:
  default:
    navigation: navigation
    footer: footer
    system-messages-2702: system-messages-7972
    logo-3313: logo-9608
    spacer-9268: spacer-2211
    menu-7641: menu-6409
    custom-9650: custom-9191
    custom-2242: custom-2229
    spacer-4819: spacer-9913
    custom-3224: custom-5952
    spacer-6169: spacer-2150
